name: Checkpoint

on:
  schedule:
    - cron: "0 18 * * 6" # 毎週日曜 03:00 JST
  workflow_dispatch:

jobs:
  checkpoint:
    uses: queria-io/dataset-shared/.github/workflows/checkpoint.yml@main
    with:
      s3_bucket: ${{ vars.S3_BUCKET }}
    secrets: inherit
