name: Sync

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "docs/**"
  schedule:
    - cron: "0 19 1 * *" # 毎月1日 04:00 JST
  workflow_dispatch:

concurrency:
  group: sync
  cancel-in-progress: false

jobs:
  sync:
    uses: queria-io/dataset-shared/.github/workflows/sync.yml@main
    with:
      dataset_name: zipcode
    secrets: inherit
